[workspace]
members = ["gulag", "synapse", "reactor"]
default-members = ["reactor"]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
rust-version = "1.85"
license = "Apache-2.0"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
overflow-checks = true
